---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: flux-system
spec:
  chart:
    spec:
      chart: version=
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 5m0s
  targetNamespace: funkwhale
  values:
    persistence:
      size: 8Gi
    postgresqlDatabase: funkwhale
    postgresqlUsername: funkwhale

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: funkwhale
  namespace: flux-system
spec:
  chart:
    spec:
      chart: funkwhale
      sourceRef:
        kind: HelmRepository
        name: ananace
  interval: 5m0s
  targetNamespace: funkwhale
  values:
    djangoSecret: insecure-secret
    ingress:
      enabled: false
    persistence:
      enabled: true
      size: 25Gi
      storageClass: rook-nfs-share1

