---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: flux-system
spec:
  chart:
    spec:
      chart: bitnami/postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 10.2.8
  interval: 12h0m0s

