apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: funkwhale-postgres-data
  namespace: funkwhale
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
