---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 12.1.1
  interval: 5m0s
  targetNamespace: funkwhale
  values:
    cluster:
      enabled: false
    master:
      persistence:
        size: 10Gi

